apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  image: 566420885017.dkr.ecr.ap-southeast-1.amazonaws.com/testjgq
  interval: 1m0s
  secretRef:
    name: ecr-credentials
