apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: default
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: 566420885017.dkr.ecr.ap-southeast-1.amazonaws.com/testjgq:5.0.0 # {"$imagepolicy": "flux-system:podinfo"}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecr-credentials 
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-nginx
